# Generated by Django 3.2.9 on 2023-01-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='seats2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
