# Generated by Django 3.2.9 on 2023-01-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_table_seats2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='table',
            name='seats2',
            field=models.IntegerField(default=2),
        ),
    ]
