# Generated by Django 3.2.9 on 2023-01-24 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_table_seats2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tables',
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='booking.table'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_dates',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
